### ISSUE TITLE
Plugin Severe error, creates config but doesnt run

### ISSUE THREAD

**Issue by TroyMLP** [DominicLuidold/SimpleBroadcast#26]
2016-01-22 19:27:42 [SEVERE] Error occurred while enabling SimpleBroadcast v1.9.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
    at net.simplebroadcast.methods.Methods.onlinePlayers(Methods.java:52)
    at net.simplebroadcast.methods.Methods.addVariables(Methods.java:197)
    at net.simplebroadcast.Commands.<init>(Commands.java:33)
    at net.simplebroadcast.Main.onEnable(Main.java:72)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:467)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:278)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:260)
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:521)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:428)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

This server is running MCPC+ version git-MCPC-Plus-jenkins-MCPC-Plus-164-251 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT)

Anything else that you need please let me know

**Comment by KingDome24** [comment]
Hello,

this seems like a bug. I'll have a look into it.

Kind regards,
KingDome24
